### ISSUE TITLE
Team Members: Import images and set featured image

### ISSUE THREAD

**Issue by wpalchemist** [RagtagOpen/freefrom-website#54]
This is the same task we are doing for posts: https://github.com/RagtagOpen/freefrom-website/issues/53

* Edit a team member
* Update the team member (you haven't made any changes to it yet, but saving it will force the images to import)
* In the sidebar, click on Featured Image.  Find the first image in the post and set it as the featured image.
* Delete the first image from the team member body so it doesn't show up twice.

**Comment by melchoyce** [comment]
Looks like there's a display issue with the featured image: https://freefrom.mystagingwebsite.com/team_member/tiff-hernandez/

![image](https://user-images.githubusercontent.com/2846578/121969224-d1b80b00-cd41-11eb-874d-5b1c8f21beb3.png)

**Comment by melchoyce** [comment]
Content should all be updated now 👍
