### ISSUE TITLE
About page adjustments

### ISSUE THREAD

**Issue by wpalchemist** [RagtagOpen/freefrom-website#57]
The about page needs the following fixes:

- [x] crop the image so that we see the women's full heads and not their legs 
- [ ] make the font bold and bigger in the "about FreeFrom" section at the top
- [ ] in the "our team" section, make the font bold

**Comment by melchoyce** [comment]
> make the font bold and bigger in the "about FreeFrom" section at the top

According to the mockups this should be semibold, but I don't have a way of updating it. For now, I've changed it to bold.

> in the "our team" section, make the font bold

I bolded the link, and increased the size of to match the mockups — should I also bold the paragraph, even though it's regular in the mocks?

**Comment by wpalchemist** [comment]
I think the bold text is fine for the section at the top, and let's leave the paragraph in the "our team" section as-is and see if it comes up in UAT
