### ISSUE TITLE
"Our Team" page improvements

### ISSUE THREAD

**Issue by wpalchemist** [RagtagOpen/freefrom-website#59]
Improvements to the "Our Team" page:

- [x] The links to "more about" each person are inconsistent - some of them have big text and some of them are small.  They should all be small to match the design.
- [x] The last row of team members only has 2 people in it, so they are only in 2 columns instead of 3, which means they are a lot bigger than the other team members. That last row should have three columns and the third column should be empty so they are all the same size.
- [x] "See all job openings" needs to link to https://freefrom.mystagingwebsite.com/employment/

**Comment by melchoyce** [comment]
> The links to "more about" each person are inconsistent - some of them have big text and some of them are small. They should all be small to match the design.

Looks like the size difference was coming from `.wp-block-button__link.has-background`. The buttons had backgrounds defined by default in the pattern; I must have removed one from the button in third column and then it stuck around when I duplicated it for the rest of the rows.

**Comment by melchoyce** [comment]
Regardless, these are all done now. (I don't have permission to check off lists or close issues.)
