### ISSUE TITLE
Employment page

### ISSUE THREAD

**Issue by wpalchemist** [RagtagOpen/freefrom-website#60]
The job openings list on the employment page doesn't match the design.  The heading font size needs to be smaller, the image should go to the edge of the wrapper, and there should be a gap between the job openings.

How it looks on the site:
![Image 2021-06-12 at 10 12 58 AM](https://user-images.githubusercontent.com/16658165/121784091-c8bf1200-cb66-11eb-94e4-d8242d381401.jpg)

How it looks in the design:
![Image 2021-06-12 at 10 13 22 AM](https://user-images.githubusercontent.com/16658165/121784101-d8d6f180-cb66-11eb-823d-24c8b5c7f997.jpg)

**Comment by melchoyce** [comment]
I was able to fix the images and the spacing within the editor, but the font sizing should probably be done with CSS, so I'm going to leave that.
